#!/bin/bash
# script for Mount EFI
# chris1111 

#Filename of Application.
APP="StatusBarApp"
HELPER="RtWlanHelper"
INF_NAME="netrtwlanu.inf"
AUX_PATH="com.realtek.utility.wifi"


#APP location.
ROOT_PATH="/Library/Application Support/WLAN"
AUX_PATH="com.realtek.utility.wifi"
UTILITY_SOCK_NAME="/var/tmp/com.realtek.utility.statusbar.socket"


echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"


#############################################################################
DEST_VOL="${3}"
if [[ $(mount | awk '$3 == "/Volumes/EFI" {print $3}') != "" ]]; then
 hdiutil Unmount "/Volumes/EFI"
fi

if [[ $(mount | awk '$3 == "/Volumes/ESP" {print $3}') != "" ]]; then
 hdiutil Unmount "/Volumes/ESP"
fi
Sleep 3

./MountESP /"$3"/

Sleep 2
echo " ---------------------------------------------
Cleanup EFI "



cp -R /"$3"/Private/tmp/EFI /Volumes/ESP

rm -rf /"$3"/Private/tmp/EFI

sudo mv "$ROOT_PATH/$HELPER" "$ROOT_PATH/$AUX_PATH/"
sudo chmod -R 777 "$ROOT_PATH/$AUX_PATH/"


# Remove link to the partition that contain the EFI folder
rm -rf "${DEST_VOL}"/EFIROOTDIR


exit 0



		
